SELECT *
FROM EMPLOYEES
WHERE SALARY BETWEEN 12000 AND 15000;

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-01-2012' AND '31-12-2021';

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE NOT BETWEEN '01-01-2012' AND '31-12-2021';

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (90, 80, 100, 60);

SELECT *
FROM COUNTRIES
WHERE REGION_ID IN (10, 20);

SELECT *
FROM COUNTRIES
WHERE REGION_ID NOT IN (10, 20);

SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL;

SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL; 

SELECT *
FROM EMPLOYEES
WHERE LAST_NAME = '&ApellidoKing';

SELECT *
FROM EMPLOYEES
WHERE LAST_NAME = '&&ApellidoKing';

SELECT *
FROM EMPLOYEES
WHERE &CONDITION;

SELECT UPPER(FIRST_NAME)||' '|| LOWER (LAST_NAME) AS "NOMBRE_MAY APELLID_MIN" 
FROM EMPLOYEES;

SELECT  LPAD('*',6 ,RPAD(' ',6,'*'))
FROM EMPLOYEES;

SELECT  LPAD('*',6 ,RPAD(' ',6,' '))
FROM EMPLOYEES;
