SELECT FIRST_NAME, DEPARTMENT_NAME 
FROM EMPLOYEES E 
INNER JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT FIRST_NAME, DEPARTMENT_NAME 
FROM EMPLOYEES E 
LEFT JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT FIRST_NAME, DEPARTMENT_NAME 
FROM EMPLOYEES E 
RIGHT JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES NATURAL JOIN DEPARTMENTS;

SELECT FIRST_NAME, DEPARTMENT_NAME 
FROM EMPLOYEES E 
FULL OUTER JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES CROSS JOIN DEPARTMENTS;

SELECT FIRST_NAME, REGION_NAME
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
INNER JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
INNER JOIN COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID
INNER JOIN REGIONS R
ON C.REGION_ID = R.REGION_ID;

SELECT E.FIRST_NAME EMPLOYEE_NAME, M.FIRST_NAME MANAGER_NAME
FROM EMPLOYEES E INNER JOIN EMPLOYEES M
ON E.MANAGER_ID = M.MANAGER_ID;

SELECT MAX(SALARY)
FROM EMPLOYEES;

SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY  DEPARTMENT_ID
ORDER BY MAX(SALARY) DESC;

SELECT DEPARTMENT_ID, MAX(SALARY), SUM(SALARY) SUMA_SALARY, ROUND(AVG(SALARY),0) PROMEDIO ,COUNT(SALARY) CONTEO
FROM EMPLOYEES
GROUP BY  DEPARTMENT_ID
ORDER BY MAX(SALARY) DESC;





