SELECT FIRST_NAME, LAST_NAME, SALARY, SALARY*0.10
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY, SALARY*0.10, SALARY*COMMISSION_PCT
FROM EMPLOYEES;

SELECT FIRST_NAME AS nombre, LAST_NAME AS apellido, SALARY AS salario, SALARY*0.10 AS salario_10pct, SALARY*COMMISSION_PCT AS salario_comision
FROM EMPLOYEES;

SELECT FIRST_NAME AS "nombre", LAST_NAME AS "apellido", SALARY AS "salario", SALARY*0.10 AS "salario_10pct", SALARY*COMMISSION_PCT AS "salario_comision"
FROM EMPLOYEES;

SELECT FIRST_NAME AS "nombre", LAST_NAME AS "apellido", SALARY AS "salario", SALARY*0.10 AS "salario_10pct", SALARY*COMMISSION_PCT AS "salario_comision", FIRST_NAME||LAST_NAME AS "nombre_apellido" 
FROM EMPLOYEES;

SELECT FIRST_NAME AS "nombre", LAST_NAME AS "apellido", SALARY AS "salario", SALARY*0.10 AS "salario_10pct", SALARY*COMMISSION_PCT AS "salario_comision", FIRST_NAME||' '||LAST_NAME AS "nombre_apellido" 
FROM EMPLOYEES;

SELECT DISTINCT REGION_ID
FROM COUNTRIES;

SELECT *
FROM EMPLOYEES
WHERE LAST_NAME = 'King' ;

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE > '01-01-2014' ;

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'An%';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a%';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%n';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_o%';

SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;


SELECT *
FROM EMPLOYEES
WHERE SALARY > 5000
AND DEPARTMENT_ID = 90;

SELECT *
FROM EMPLOYEES
WHERE SALARY > 5000
OR DEPARTMENT_ID = 80;

SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC;
