SELECT ROUND (555,-3)
FROM DUAL;

SELECT ROUND (15,-1)
FROM DUAL;

SELECT TRUNC (15.9457, -1)
FROM DUAL;

SELECT last_name, hire_date, hire_date + 1 AS fecha_ajustada
FROM employees

SELECT '15/05/2007', TO_DATE('15/05/2007','DD/MM/YY')AS YY
FROM DUAL;

SELECT '15/05/07', TO_DATE('15/05/07','DD/MM/RR')AS RR
FROM DUAL;

SELECT sysdate
FROM dual;

SELECT SESSIONTIMEZONE, CURRENT_DATE
FROM DUAL;

SELECT SESSIONTIMEZONE, CURRENT_DATE - TO_DATE('15/05/2007','DD/MM/YY') 
FROM DUAL;

SELECT  ROUND((CURRENT_DATE - TO_DATE('15/05/2007','DD/MM/YY'))*86400, 0)DIAS
FROM DUAL;

SELECT ROUND(TO_DATE('25/04/26','DD/MM/YY') -2,'MM' )-1 FECHA  
FROM dual;

SELECT ROUND(MONTHS_BETWEEN(CURRENT_DATE, '15/05/07'), 0) MESES_VIVIDOS
FROM DUAL;

SELECT ADD_MONTHS(CURRENT_DATE, 1)
FROM DUAL;

SELECT LAST_DAY(CURRENT_DATE)
FROM DUAL;

SELECT NEXT_DAY(LAST_DAY(ADD_MONTHS(CURRENT_DATE, &MES))-7,'VIERNES')
FROM DUAL;
